version: '3.9'

services:
  postgresql:
    image: postgres
    container_name: db-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: postgres
    restart: always


  redis:
    image: redis:alpine3.20
    container_name: db-redis
    ports:
      - "6379:6379"